"@id_", "@type_", "affects__type_", "affects__value__0_", "consequence__type_", "consequence__value_", "description__type_", "description__value_", "event__type_", "event__value_", "isOutputOf__type_", "isOutputOf__object__0_", "isOutputOf__object__1_", "linkTo__type_", "linkTo__value__0_", "location__@type_", "location__value__type_", "location__value__coordinates__0__0__0_", "location__value__coordinates__0__0__1_", "location__value__coordinates__0__1__0_", "location__value__coordinates__0__1__1_", "location__value__coordinates__0__2__0_", "location__value__coordinates__0__2__1_", "location__value__coordinates__0__3__0_", "location__value__coordinates__0__3__1_", "location__value__coordinates__0__4__0_", "location__value__coordinates__0__4__1_", "mitigatedBy__type_", "mitigatedBy__value__0_", "severity__type_", "severity__value_", "sourceRisk__type_", "sourceRisk__object__0_", "threat__type_", "threat__value_", "validFrom__type_", "validFrom__value__@type_", "validFrom__value__@value_", "validTo__type_", "validTo__value__@type_", "validTo__value__@value_", "@context__0_"
"urn:ngsi-ld:Risk:01", "Risk", "Relationship", "urn:ngsi-ld:ServiceGISData:01", "Property", "Reputation", "Property", "Risk01 Corresponds to a failure in the Pumps of the water infraestructure", "Property", "interruption", "Relationship", "urn:ngsi-ld:EOGeoDataLayer:01", "urn:ngsi-ld:EOGeoDataLayer:01", "Relationship", "urn:ngsi-ld:Risk:02", "GeoProperty", "Polygon", "23.6627", "41.88768", "25.85598", "43.38622", "23.4899", "43.78691", "22.35609", "42.28869", "23.6627", "41.88769", "Relationship", "urn:ngsi-ld:Mitigation:01", "Property", "MEDIUM", "Relationship", "urn:ngsi-ld:Attacker:01", "Property", "physical", "Property", "DateTime", "2021-02-18T12:00:00Z", "Property", "DateTime", "2021-02-18T12:00:00Z", "https://raw.githubusercontent.com/smart-data-models/dataModel.RiskManagement/master/context.jsonld"